//
//  YTPlayerInteractor.swift
//  player
//
//  Created by Warakorn T on 26/3/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//Ï

import UIKit

protocol YTPlayerBusinessLogic {
    func loadYoutubeVideo(request: YTPlayer.LoadYoutubeVideo.Request)
}

protocol YTPlayerDataStore {
    //var name: String { get set }
}

class YTPlayerInteractor: YTPlayerBusinessLogic, YTPlayerDataStore {
    var presenter: YTPlayerPresentationLogic?
    var worker: YTPlayerWorker?
    //var name: String = ""
    
    func loadYoutubeVideo(request: YTPlayer.LoadYoutubeVideo.Request) {
        let response = YTPlayer.LoadYoutubeVideo.Response(id: request.id)
        presenter?.presentLoadYoutubeVideo(response: response)
    }
}
